[package]
name = "lis3dh-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "1.0.1", optional = true }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
fmt = "0.1.0"
panic-halt = "1.0.0"
paste = "1.0.15"

[lib]
path = "src/lib.rs"

[features]
defmt = ["dep:defmt"]
